# .readthedocs.yaml
# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# Specify the version of the ReadTheDocs configuration file
version: 2

# Python version to use
# Set the version of Python and other tools you might need
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"

# Sphinx documentation options
sphinx:
  configuration: docs/build/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
