
Reading phylip file /Users/tyler/programs/PG-SUI/simulation/sim_c0.001_s0.009/c0.001_s0.009_gtrgamma/c0.001_s0.009_gtrgamma_i0.0_base-snps-concat.phylip...
Done!

Converting genotypes to one-hot encoding...
Done!

Converting genotypes to 012 encoding...
Done!

Adding 0.1 missing data using strategy: random
Doing VAE imputation without grid search...
