{% set name = "pg-sui" %}
{% set version = "1.2.1" %}
{% set license = "GPL-3.0-or-later" %}
{% set github_url = "https://github.com/btmartin721/PG-SUI" %}

package:
  name: {{ name|lower }}
  version: {{ version }}"

source:
  git_url: {{ github_url }}
  git_branch: dev_btm_pt

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

description:
  home: {{ github_url }}
  summary: "Python machine and deep learning API to impute missing genotypes."
  license: {{ license }}
  license_file: LICENSE
  doc_url: https://pg-sui.readthedocs.io/en/latest/

requirements:
  host:
    - python >=3.11,<3.12
    - pip
    - setuptools
  run:
    - python >=3.11,<3.12
    - matplotlib
    - numpy >=2.1
    - optuna
    - pandas >=2.2.2
    - pytorch
    - scikit-learn >=1.4
    - scipy
    - seaborn
    - snpio
    - toytree
    - tqdm
    - xgboost
    
about:
  summary: "Python machine and deep learning API to impute missing genotypes."
  description: |
    PG-SUI is a Python library designed to facilitate imputation of missing genotypes using machine learning and deep learning methods. It supports unsupervised and supervised methods and includes tools for integration with population genetics workflows.
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/btmartin721/PG-SUI

extra:
  recipe-maintainers:
    - evobio721
